language: python
cache: pip
python:
    - 3.5
    - 3.6
install:
    - pip install -e .
    - pip install pipenv --upgrade
    - pipenv install --dev --three
script:
    - pipenv run py.test --cov=umbral
